# Generated by Django 3.1.7 on 2021-03-15 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField()),
                ('duree_en_minutes', models.IntegerField()),
                ('nombre_maximal_inscriptions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maximal_inscriptions_file_attente', models.IntegerField()),
                ('date', models.DateField()),
                ('reservations_prioritaires', models.BooleanField()),
                ('liste_prioritaire', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_avantageuse', to='distribution.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionCreneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs', to=settings.AUTH_USER_MODEL)),
                ('creneau_horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_creneaux', to='distribution.creneauhoraire')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionAttente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_file_attente', to=settings.AUTH_USER_MODEL)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_en_attente', to='distribution.distribution')),
            ],
        ),
        migrations.AddField(
            model_name='creneauhoraire',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='distribution.distribution'),
        ),
        migrations.CreateModel(
            name='ColisNonRecupere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_manques', to=settings.AUTH_USER_MODEL)),
                ('creneau_horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis_non_recuperes', to='distribution.creneauhoraire')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('masculin', 'masculin'), ('féminin', 'féminin')], default='masculin', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
