# Generated by Django 3.1.7 on 2021-03-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='liste_prioritaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_avantageuse', to='distribution.distribution'),
        ),
    ]
